[workspace]
resolver="2"
members = [
    "core",
    "gateway",
    "tools"
]

[workspace.dependencies]
# Phase 0 Standard (Feb 2026)
tokio = { version = "1.43", features = ["full"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
anyhow = "1.0.95"
tracing = "0.1.41"